# Generated by Django 2.0.3 on 2018-04-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puc',
            name='done',
            field=models.CharField(default='true', max_length=55),
        ),
    ]
