# Generated by Django 2.0.3 on 2018-04-01 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puc', '0002_puc_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='puc',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2018, 4, 1, 10, 32, 31, 54299)),
        ),
    ]
