# Generated by Django 2.0.3 on 2018-04-01 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puc', '0003_puc_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puc',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2018, 4, 1, 11, 0, 11, 958008)),
        ),
    ]
