# Generated by Django 2.0.3 on 2018-04-01 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puc', '0004_auto_20180401_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puc',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2018, 4, 1, 14, 35, 22, 937433)),
        ),
    ]
