# Generated by Django 2.0.3 on 2018-03-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=55)),
                ('social_media_id', models.CharField(max_length=55)),
                ('social_media', models.CharField(max_length=55)),
            ],
        ),
    ]
