# Generated by Django 2.0.3 on 2018-04-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadharUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharN', models.CharField(max_length=55)),
                ('phoneNumber', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=55)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'CAR\\Jeep\\Van'), ('LCV', 'LCV'), ('BUS', 'BUS\\TRUCK'), ('HCM\\EME', 'HCM\\EME'), ('UPTO3AXLE', 'upto 3 axel'), ('4-6 AXLE', '4 to 6 axel'), ('7AXLE+', '7 axle or above')], max_length=55)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.AadharUser')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
