# Generated by Django 2.0.3 on 2018-04-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20180401_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('amount_vehicle_car', models.IntegerField()),
                ('amount_vehicle_truck', models.IntegerField()),
                ('amount_vehicle_lcv', models.IntegerField()),
                ('amount_vehicle_3axel', models.IntegerField()),
                ('amount_vehicle_4to6axel', models.IntegerField()),
                ('amount_vehicle_7axel', models.IntegerField()),
                ('amount_vehicle_hcm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TollPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.VehicleUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='toll',
            unique_together={('name', 'location')},
        ),
    ]
