# Generated by Django 2.0.3 on 2018-04-01 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollpayment',
            name='toll',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='toll.Toll'),
        ),
    ]
